Add feature type and feature name handling
mdabros/XGBoostSharp pull request #36
Opened 2024-11-14 08:16 UTC by madskonradsen

Right now, the DMatrix is internal to the booster, but it might make sense to simply let people pass into a DMatrix directly to the classifier/regressor?

2024-11-17 19:41 UTC, mdabros commented
> Right now, the DMatrix is internal to the booster, but it might make sense to simply let people pass a DMatrix directly to the classifier/regressor?

Yes, I think that would be a good idea to provide more control for more advanced use cases. We can keep the float array overloads for the more basic/easy cases.

2024-11-17 19:41 UTC, mdabros commented
I will try to review the PR this week.

2024-11-17 20:17 UTC, madskonradsen commented
Added the overloads for DMatrix and basic tests just to make use of them

2024-11-20 16:17 UTC, mdabros requested changes
@madskonradsen I have added a few comments and suggestions - nothing major :). Besides that it looks good 👍 .

2024-11-20 16:17 UTC, mdabros commented on src/XGBoostSharp/lib/DMatrix.cs
> +        SetFeatureInfo(featureNames, "feature_name");
@madskonradsen Let's move the hardcoded strings to a `Fields` class, so we only define them in one place. like this:

```csharp
namespace XGBoostSharp.lib;

public static class Fields
{
#pragma warning disable IDE1006 // Naming Styles
    public const string label = nameof(label);
    public const string feature_name = nameof(feature_name);
    public const string feature_type = nameof(feature_type);
#pragma warning restore IDE1006 // Naming Styles
}
```

2024-11-20 16:17 UTC, mdabros commented on src/XGBoostSharp/lib/DMatrix.cs
> +    public string[] GetFeatureTypes()
@madskonradsen For these one-liner methods please use:
```csharp
    public string[] GetFeatureTypes() => GetFeatureInfo(Fields.feature_type);
```

2024-11-20 16:17 UTC, mdabros commented on src/XGBoostSharp/XGBClassifier.cs
> +    public float[] Predict(DMatrix dMatrix)
@madskonradsen Where possible, we might as well reuse and call the new DMatrix overload methods from the old float based methods. For both `Predict` and `Fit` methods, and for both the regressor and the classifier implementations.

2024-11-20 16:17 UTC, mdabros commented on src/XGBoostSharp.Tests/DMatrixTest.cs
> +        var sut = new DMatrix(m_dataTrain, m_labelsTrain);
@madskonradsen Remember using statement for the DMatrix:
```csharp
using var sut = new DMatrix(m_dataTrain, m_labelsTrain);
```
Same for the the other tests.

2024-11-20 18:08 UTC, madskonradsen commented
Fair points, have fixed accordingly! :)

2024-11-21 08:11 UTC, mdabros commented
> Fair points, have fixed accordingly! :)

Looks good. I will merge and release a new version with the additions. Thanks for the contribution!

2024-11-21 08:11 UTC, merged